### ISSUE TITLE
How to dynamically make links in navigation "active"

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-fall2017#157]
[Here's a quick video (4:43) showing how to dynamically make links in your navigation "active"](https://www.youtube.com/embed/8KaLtYBsj38?rel=0&showinfo=0)

Final code: [/views/modules/nav.blade.php](https://github.com/susanBuck/foobooks/blob/master/resources/views/modules/nav.blade.php)

And here's the CSS code I have in `foobooks.css` which corresponds to the `active` class being added to the links in the videos:

```css
a.active:link, a.active:visited, a.active:active, a.active:hover {
    color:#18bc9c;
}
```
(from [public/css/foobooks.css#L97](https://github.com/susanBuck/foobooks/blob/master/public/css/foobooks.css#L97))
